### ISSUE TITLE
Chat Overlay Missing Feature

### ISSUE THREAD

**Issue by bypiffa** [tuxfoo/nodecg-odysee-bundles#11]
I have a problem with chat overlays. And again. It's probably due to me, not being able to find a setting.

 - **Chat Timeout**. A feature that removes chat messages some time after it's being shown.

**Comment by tuxfoo** [comment]
this would be a good feature. I will add it.

**Comment by tuxfoo** [comment]
I have added this feature https://github.com/tuxfoo/simple-chat/commit/5e64b807ded8153f8568f4352b29926f7e901350
I will include it in the next portable release.

If you would like to try it before the next portable release then you can download the latest simple-chat bundle.
https://github.com/tuxfoo/simple-chat/archive/refs/heads/main.zip

Stop nodecg
Delete the old simple-chat bundle folder from nodecg-portable/bundles/
Extract the contents of main.zip into nodecg-portable/bundles/
Rename simple-chat-main to just simple-chat
Star nodecg, in the dashboard set the timeout option in the simple-chat settings.

**Comment by tuxfoo** [comment]
Added this feature to the 0.0.7 release

https://github.com/tuxfoo/odysee-simple-alerts-connector/releases/tag/0.0.7-alpha
