### ISSUE TITLE
Message Fade-Out doesn't seem to work

### ISSUE THREAD

**Issue by bypiffa** [tuxfoo/nodecg-odysee-bundles#13]
# We tested this feature ...
![image](https://user-images.githubusercontent.com/74742244/119417857-71641980-bcff-11eb-92f9-2e734d918aa6.png)
# Pressed Reload Button 
![image](https://user-images.githubusercontent.com/74742244/119417962-a40e1200-bcff-11eb-8dd6-c2ffa22d6b20.png)

# but the fade-out doesnt seem to work, for some reason.

We used [this](https://github.com/tuxfoo/nodecg-odysee-bundles/releases/tag/0.0.7-alphahttps://github.com/tuxfoo/nodecg-odysee-bundles/releases/tag/0.0.7-alpha) release.

**Comment by tuxfoo** [comment]
Sorry about that. Could you try the hotfix (Still the 0.0.7 release, I just updated all the files) https://github.com/tuxfoo/nodecg-odysee-bundles/releases/tag/0.0.7-alpha
