### ISSUE TITLE
No license.

### ISSUE THREAD

**Issue by JYamihud** [tuxfoo/nodecg-odysee-bundles#14]
I was going to promote your program but I realized it's not free. Since there is no license providing people with the 4 freedoms. Please add the license. Just having the source code is not enough.

From [gnu.org about licenses](https://www.gnu.org/licenses/license-list.html):

> If source code does not carry a license to give users the four essential freedoms, then unless it has been explicitly and validly placed in the public domain, it is not free software.
>
> Some developers think that code with no license is automatically in the public domain. That is not true under today's copyright law; rather, all copyrightable works are copyrighted by default. This includes programs. Absent a license to grant users freedom, they don't have any. In some countries, users that download code with no license may infringe copyright merely by compiling it or running it.
>
> In order for a program to be free, its copyright holders must explicitly grant users the four essential freedoms. The document with which they do so is called a free software license. This is what free software licenses are for.
>
> Some countries allow authors to put code in the public domain, but that requires explicit action. If you wish to do that, the method we recommend is to use CC0, which also works in other countries by putting on a license that is more or less equivalent to public domain. However, in most cases it is better to copyleft your code to assure that freedom reaches all users of the code.
>
> Code written by employees of the US government is a special exception, since US copyright law explicitly puts that in the public domain; but this does not apply to works that the US pays a company to write. It also does not apply to other countries, many of which do allow the state to have a copyright on government writings.

**Comment by tuxfoo** [comment]
Added MIT License

https://github.com/tuxfoo/simple-chat/commit/ec7b4e9f4d7704c12f3f819c2b21c26dc066e170
https://github.com/tuxfoo/nodecg-odysee-bundles/commit/20c21045485df1c45a75824d05c895b7a7deb4a0
